In [6]:
import matplotlib.pyplot as plt
import numpy as np
import sys, os
sys.path.append(os.pardir)
sys.path.append("../../")
from dataset.mnist import load_mnist
from sklearn.datasets import load_iris
from logisticReg import Lreg

In [7]:
iris = load_iris()
X = iris.data
Y = iris.target

iris_Y = Y.copy()
# 원 핫 인코딩
num = np.unique(Y,axis=0)
num = num.shape[0]
Y = np.eye(num)[Y].astype(np.int)

y_name = iris.target_names

In [18]:
reg = Lreg(X.shape[1],y_name.shape[0],"m")

In [19]:
batch_num = 20
for j in range(200):
    sample = np.random.randint(0,X.shape[0],batch_num)
    reg.learn(X[sample],Y[sample])
    print(reg.cost(X[sample],Y[sample]))

[1.077 0.877 0.555]
[0.634 1.252 0.355]
[0.555 1.187 0.324]
[0.379 0.834 0.363]
[0.496 1.186 0.315]
[0.533 1.251 0.297]
[0.477 1.006 0.307]
[0.467 0.776 0.266]
[0.370 0.897 0.364]
[0.410 0.934 0.316]
[0.376 0.731 0.270]
[0.267 0.859 0.384]
[0.322 0.840 0.308]
[0.338 0.853 0.326]
[0.294 0.754 0.367]
[0.305 0.580 0.236]
[0.299 0.653 0.262]
[0.270 0.748 0.304]
[0.284 0.878 0.281]
[0.242 0.750 0.336]
[0.200 0.696 0.333]
[0.241 0.599 0.259]
[0.206 0.479 0.228]
[0.230 0.662 0.275]
[0.229 0.382 0.175]
[0.221 0.608 0.202]
[0.183 0.631 0.329]
[0.200 0.665 0.285]
[0.169 0.616 0.298]
[0.207 0.673 0.298]
[0.226 0.732 0.208]
[0.209 0.670 0.228]
[0.193 0.635 0.257]
[0.169 0.690 0.265]
[0.137 0.589 0.308]
[0.146 0.337 0.222]
[0.172 0.616 0.237]
[0.163 0.677 0.226]
[0.160 0.675 0.284]
[0.135 0.420 0.207]
[0.161 0.653 0.289]
[0.147 0.666 0.281]
[0.142 0.559 0.274]
[0.118 0.693 0.355]
[0.126 0.476 0.219]
[0.189 0.618 0.196]
[0.138 0.598 0.264]
[0.127 0.652 0.263]
[0.091 0.663 0.354]
[0.159 0.622 0.233]


In [20]:
T1 = reg.predict(X).argmax(1)

same1 = 0
for i in range(iris_Y.shape[0]):
    if(T1[i] == iris_Y[i]): same1+=1

print(same1/T1.size)

0.9666666666666667


In [21]:
(x_train, t_train), (x_test, t_test) =load_mnist(flatten=True, normalize=True)
label_name = np.array(['0','1','2','3','4','5','6','7','8','9'])
rY = t_train.copy()
eY = t_test.copy()
num = np.unique(t_train,axis=0)
num = num.shape[0]
t_train = np.eye(num)[t_train].astype(np.int)

num2 = np.unique(t_test,axis=0)
num2 = num2.shape[0]
t_test = np.eye(num)[t_test].astype(np.int)

In [22]:
reg2 = Lreg(x_train.shape[1],label_name.shape[0],"m")

In [23]:
batch_num = 30
for j in range(1000):
    sample = np.random.randint(0,x_train.shape[0],batch_num)
    reg2.learn(x_train[sample],t_train[sample])
    if(j%100 ==99):
        print(reg2.cost(x_train[sample],t_train[sample]))

[0.082 0.069 0.148 0.101 0.084 0.330 0.053 0.079 0.139 0.099]
[0.037 0.071 0.074 0.151 0.093 0.151 0.037 0.042 0.105 0.173]
[0.030 0.115 0.123 0.047 0.218 0.111 0.041 0.078 0.037 0.115]
[0.050 0.048 0.156 0.084 0.041 0.180 0.033 0.034 0.124 0.072]
[0.026 0.013 0.168 0.075 0.043 0.159 0.177 0.012 0.050 0.054]
[0.052 0.020 0.089 0.073 0.047 0.084 0.068 0.098 0.190 0.058]
[0.038 0.036 0.024 0.034 0.237 0.034 0.214 0.115 0.245 0.041]
[0.016 0.041 0.201 0.035 0.053 0.120 0.054 0.092 0.129 0.104]
[0.021 0.018 0.018 0.072 0.054 0.105 0.020 0.052 0.128 0.107]
[0.016 0.032 0.115 0.035 0.017 0.100 0.038 0.029 0.096 0.056]


In [24]:
T = reg2.predict(x_test).argmax(1)
same = 0
for i in range(eY.shape[0]):
    if(T[i] == eY[i]): same+=1

print(same/T.size)

0.8959
